//
//  MyStyleKit.h
//  kdeconnect
//
//  Created by YANG Qiao on 8/5/14.
//  Copyright (c) 2014 (null). All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface MyStyleKit : NSObject

// Colors
+ (UIColor*)navbar;
+ (UIColor*)buttonNormal;
+ (UIColor*)buttonHighlighted;
+ (UIColor*)intro;
+ (UIColor*)intro1;
+ (UIColor*)intro2;
+ (UIColor*)intro3;

// Drawing Methods
+ (void)drawPlay;
+ (void)drawPlayHighlighted;
+ (void)drawPause;
+ (void)drawPauseHighlighted;
+ (void)drawForward;
+ (void)drawForwardHighlighted;
+ (void)drawBack;
+ (void)drawBackHighlighted;
+ (void)drawPrevious;
+ (void)drawPreviousHighlighted;
+ (void)drawFollowing;
+ (void)drawFollowingHighlighted;
+ (void)drawMousePadIntro;
+ (void)drawMousePadIntro1Small;
+ (void)drawMousePadIntro2Small;
+ (void)drawMousePadIntro3Small;
+ (void)drawMousePadIntro4Small;
+ (void)drawGear;
+ (void)drawGearHighlighted;
+ (void)drawMore;
+ (void)drawMoreHighlighted;

// Generated Images
+ (UIImage*)imageOfPlay;
+ (UIImage*)imageOfPlayHighlighted;
+ (UIImage*)imageOfPause;
+ (UIImage*)imageOfPauseHighlighted;
+ (UIImage*)imageOfForward;
+ (UIImage*)imageOfForwardHighlighted;
+ (UIImage*)imageOfBack;
+ (UIImage*)imageOfBackHighlighted;
+ (UIImage*)imageOfPrevious;
+ (UIImage*)imageOfPreviousHighlighted;
+ (UIImage*)imageOfFollowing;
+ (UIImage*)imageOfFollowingHighlighted;
+ (UIImage*)imageOfMousePadIntro;
+ (UIImage*)imageOfMousePadIntro1Small;
+ (UIImage*)imageOfMousePadIntro2Small;
+ (UIImage*)imageOfMousePadIntro3Small;
+ (UIImage*)imageOfMousePadIntro4Small;
+ (UIImage*)imageOfGear;
+ (UIImage*)imageOfGearHighlighted;
+ (UIImage*)imageOfMore;
+ (UIImage*)imageOfMoreHighlighted;

@end
